-- 2026-08-05 place-id backfill (gap-only, idempotent)
-- Source: scripts/place-ids.json. Enables the exact venue_requests join.
update venues set google_place_id = 'ChIJd3-uGZ1ZwokR2fCvxWdgWqY' where name = 'The Grafton' and google_place_id is null;
update venues set google_place_id = 'ChIJLXPphJxZwokRNVmngCybEpQ' where name = 'Standings' and google_place_id is null;
update venues set google_place_id = 'ChIJlUueGJ1ZwokRlBb3NEfYFF8' where name = 'International Bar' and google_place_id is null;
update venues set google_place_id = 'ChIJ7buqpp1ZwokRk-t076OO99E' where name = 'Coyote Ugly Saloon' and google_place_id is null;
update venues set google_place_id = 'ChIJq-A7UZ1ZwokRC9nHZurb4iQ' where name = 'Niagara Bar' and google_place_id is null;
update venues set google_place_id = 'ChIJ3WRZYp1ZwokRI0GzAf4kCIQ' where name = 'Lucy''s Bar' and google_place_id is null;
update venues set google_place_id = 'ChIJwRcz2HdZwokR_I0BuB3PkFc' where name = 'Doc Holliday''s' and google_place_id is null;
update venues set google_place_id = 'ChIJQwDts4NZwokR1G-QaglL6H0' where name = 'The Library' and google_place_id is null;
update venues set google_place_id = 'ChIJKU1MNJ1ZwokRQ7eiWK511vI' where name = 'Death & Co' and google_place_id is null;
update venues set google_place_id = 'ChIJG4L6XndZwokR7CIyJVdM4CI' where name = 'The Summit Bar' and google_place_id is null;
update venues set google_place_id = 'ChIJWaWbwHlZwokRj1wHkvB84zE' where name = 'Alphabet City Beer Co' and google_place_id is null;
update venues set google_place_id = 'ChIJMbtTs4RZwokRB3Bd_3yH7AA' where name = 'KGB Bar' and google_place_id is null;
update venues set google_place_id = 'ChIJGdCSd5tZwokRfYvMyzO7qtE' where name = 'McSorley''s Old Ale House' and google_place_id is null;
update venues set google_place_id = 'ChIJbU-JV55ZwokRRgid16uv0jA' where name = 'Beauty Bar' and google_place_id is null;
update venues set google_place_id = 'ChIJb67-ZZ1ZwokRRxBYr3GlFp0' where name = 'Please Don''t Tell' and google_place_id is null;
update venues set google_place_id = 'ChIJZeSUWndZwokRwwxbW4B4nHM' where name = 'The Wayland' and google_place_id is null;
update venues set google_place_id = 'ChIJFTsuboNZwokRNAuw9taAIx4' where name = 'd.b.a.' and google_place_id is null;
update venues set google_place_id = 'ChIJD28DfJ5ZwokRpyv9AXrO6no' where name = 'Juke Bar' and google_place_id is null;
update venues set google_place_id = 'ChIJB2KyA51ZwokRyWZr8ZgaeRA' where name = 'Holiday Cocktail Lounge' and google_place_id is null;
update venues set google_place_id = 'ChIJI1FMYZ1ZwokRhOThOdTMOgA' where name = 'Ten Degrees' and google_place_id is null;
update venues set google_place_id = 'ChIJA9irJVtZwokRxk_y6uNanoI' where name = 'The Headless Widow' and google_place_id is null;
update venues set google_place_id = 'ChIJsctiAgBZwokRRPidYZS6VzQ' where name = 'Wonderland Bar' and google_place_id is null;
update venues set google_place_id = 'ChIJ3XASaJ1ZwokR4zn6EyjizVM' where name = 'Bua' and google_place_id is null;
update venues set google_place_id = 'ChIJbXN71WhZwokRNTk55-ScVWY' where name = 'Superbueno' and google_place_id is null;
update venues set google_place_id = 'ChIJTSEOrsNZwokR8vHwFFdZla8' where name = 'Sweet Linda' and google_place_id is null;
update venues set google_place_id = 'ChIJqTZuJztZwokREqOEPG7VOSM' where name = 'Motel No Tell' and google_place_id is null;
update venues set google_place_id = 'ChIJYTk0bpxZwokRHBO9UXg4SVA' where name = 'Solas' and google_place_id is null;
update venues set google_place_id = 'ChIJr_CugNxZwokRYRqcXtzJ8sQ' where name = 'Paradise Lost' and google_place_id is null;
update venues set google_place_id = 'ChIJm8vZD51ZwokR-5pyz5U7Omg' where name = 'Goodnight Sonny' and google_place_id is null;
update venues set google_place_id = 'ChIJe-lFm_VZwokRpZ2tEFhS6f4' where name = 'Deluxx Fluxx' and google_place_id is null;
update venues set google_place_id = 'ChIJe74ZAXdZwokR3qXA9irhjio' where name = 'Lucky' and google_place_id is null;
update venues set google_place_id = 'ChIJjZDVonZZwokRoZPvylQfyFY' where name = 'Mona''s' and google_place_id is null;
update venues set google_place_id = 'ChIJx1AoOXVZwokRe1q0RHf5t6U' where name = 'The York' and google_place_id is null;
update venues set google_place_id = 'ChIJfdFXdnZZwokRw8KBMsqlO5U' where name = 'The Spotted Owl Tavern' and google_place_id is null;
update venues set google_place_id = 'ChIJUeg8neFZwokRjTD4oCwTPGk' where name = 'Accidental Bar' and google_place_id is null;
update venues set google_place_id = 'ChIJiaPprINZwokR2C1kGvUYBfQ' where name = 'Berlin' and google_place_id is null;
update venues set google_place_id = 'ChIJ4erQS9dZwokRRAK6XSV74sg' where name = 'Little Rebel' and google_place_id is null;
update venues set google_place_id = 'ChIJ5dKgkl1ZwokRVaLe0VlqPXg' where name = 'Romeos' and google_place_id is null;
update venues set google_place_id = 'ChIJr1acrIJZwokRLpu9uKM6lIo' where name = 'Club Cumming' and google_place_id is null;
update venues set google_place_id = 'ChIJo3_m5pxZwokRyDo458xlexg' where name = 'Big Bar' and google_place_id is null;
update venues set google_place_id = 'ChIJA5VYvHZZwokR3PrQCTgoJ8g' where name = 'Two Perrys' and google_place_id is null;
update venues set google_place_id = 'ChIJd5X6lqdZwokRmTT4LVSpAl4' where name = 'Wiggle Room' and google_place_id is null;
update venues set google_place_id = 'ChIJpStBHXZZwokRP6qe0Iyqtsk' where name = '96 Tears' and google_place_id is null;
update venues set google_place_id = 'ChIJRZhgTIJZwokR5ZRVoHE3tlw' where name = 'Double Down Saloon' and google_place_id is null;
update venues set google_place_id = 'ChIJ7QfWz5VZwokRMwX7VtNhwvw' where name = 'Lovers of Today' and google_place_id is null;
update venues set google_place_id = 'ChIJMRtpqp1ZwokRewsdGXAeOOI' where name = 'Banshee' and google_place_id is null;
update venues set google_place_id = 'ChIJ-3ZSb5xZwokRDb2PQKNwwbU' where name = 'Sake Bar Decibel' and google_place_id is null;
update venues set google_place_id = 'ChIJuYldg5tZwokRsqgWxKnQQTk' where name = 'Barcade' and google_place_id is null;
update venues set google_place_id = 'ChIJdY_U5pxZwokR0A9LyTQzOz8' where name = 'Blue & Gold Tavern' and google_place_id is null;
update venues set google_place_id = 'ChIJf0AsgTxZwokRiE7wZTUENp0' where name = 'Downtown Social' and google_place_id is null;
update venues set google_place_id = 'ChIJR4DCmHZZwokRabhwmFJnhnE' where name = 'Otto''s Shrunken Head' and google_place_id is null;
update venues set google_place_id = 'ChIJK3tvLJtZwokReGHk-DS62eY' where name = 'Phebe''s Tavern' and google_place_id is null;
update venues set google_place_id = 'ChIJyVOaMJtZwokRdMND4_f_L-U' where name = 'Joyface' and google_place_id is null;
update venues set google_place_id = 'ChIJ5XAAap1ZwokRk-eUiFS2OaY' where name = 'St. Dymphna''s' and google_place_id is null;
update venues set google_place_id = 'ChIJ5UXURXdZwokR4sn8rm7f9Q4' where name = 'Nublu 151' and google_place_id is null;
update venues set google_place_id = 'ChIJ-1HxQCdZwokRLHj8Dl1rVOo' where name = 'The Ready Rooftop' and google_place_id is null;

select count(*) filter (where google_place_id is not null) as filled, count(*) from venues;
