-- Generated by scripts/emit-colleges-sql.mjs — do not hand-edit.
-- Source of truth: src/data/colleges.ts (145 schools).
-- Safe to re-run: creates if absent, upserts every row on slug.

-- ---------- colleges ----------
-- Reference list backing the onboarding picker and profiles.college_slug.
-- slug (not uuid) is the key so the app's local list and this table stay
-- readable and diffable against each other. Slugs are permanent.

create table if not exists colleges (
  slug        text primary key,
  name        text not null,
  city        text not null,
  state       text not null,
  region      text not null,
  sort_order  integer not null default 70,
  created_at  timestamptz not null default now()
);

alter table colleges enable row level security;

-- Readable by anyone signed in; writes are seed-only (service role), same
-- posture as venues.
drop policy if exists "colleges readable by authenticated" on colleges;
create policy "colleges readable by authenticated"
  on colleges for select
  using (auth.role() = 'authenticated');

insert into colleges (slug, name, city, state, region, sort_order) values
  ('hws', 'Hobart and William Smith Colleges', 'Geneva', 'NY', 'launch', 0),
  ('nyu', 'New York University', 'New York', 'NY', 'nyc', 10),
  ('columbia', 'Columbia University', 'New York', 'NY', 'nyc', 10),
  ('barnard', 'Barnard College', 'New York', 'NY', 'nyc', 10),
  ('the-new-school', 'The New School', 'New York', 'NY', 'nyc', 10),
  ('parsons', 'Parsons School of Design', 'New York', 'NY', 'nyc', 10),
  ('cooper-union', 'The Cooper Union', 'New York', 'NY', 'nyc', 10),
  ('fordham', 'Fordham University', 'New York', 'NY', 'nyc', 10),
  ('pace', 'Pace University', 'New York', 'NY', 'nyc', 10),
  ('baruch', 'Baruch College (CUNY)', 'New York', 'NY', 'nyc', 10),
  ('hunter', 'Hunter College (CUNY)', 'New York', 'NY', 'nyc', 10),
  ('ccny', 'City College of New York (CUNY)', 'New York', 'NY', 'nyc', 10),
  ('brooklyn-college', 'Brooklyn College (CUNY)', 'Brooklyn', 'NY', 'nyc', 10),
  ('queens-college', 'Queens College (CUNY)', 'Queens', 'NY', 'nyc', 10),
  ('john-jay', 'John Jay College (CUNY)', 'New York', 'NY', 'nyc', 10),
  ('fit', 'Fashion Institute of Technology', 'New York', 'NY', 'nyc', 10),
  ('sva', 'School of Visual Arts', 'New York', 'NY', 'nyc', 10),
  ('pratt', 'Pratt Institute', 'Brooklyn', 'NY', 'nyc', 10),
  ('juilliard', 'The Juilliard School', 'New York', 'NY', 'nyc', 10),
  ('marymount-manhattan', 'Marymount Manhattan College', 'New York', 'NY', 'nyc', 10),
  ('yeshiva', 'Yeshiva University', 'New York', 'NY', 'nyc', 10),
  ('st-johns', 'St. John''s University', 'Queens', 'NY', 'nyc', 10),
  ('manhattan', 'Manhattan University', 'Bronx', 'NY', 'nyc', 10),
  ('hofstra', 'Hofstra University', 'Hempstead', 'NY', 'nyc', 10),
  ('stony-brook', 'Stony Brook University', 'Stony Brook', 'NY', 'nyc', 10),
  ('cornell', 'Cornell University', 'Ithaca', 'NY', 'ny', 20),
  ('syracuse', 'Syracuse University', 'Syracuse', 'NY', 'ny', 20),
  ('rochester', 'University of Rochester', 'Rochester', 'NY', 'ny', 20),
  ('rit', 'Rochester Institute of Technology', 'Rochester', 'NY', 'ny', 20),
  ('colgate', 'Colgate University', 'Hamilton', 'NY', 'ny', 20),
  ('hamilton', 'Hamilton College', 'Clinton', 'NY', 'ny', 20),
  ('skidmore', 'Skidmore College', 'Saratoga Springs', 'NY', 'ny', 20),
  ('union', 'Union College', 'Schenectady', 'NY', 'ny', 20),
  ('vassar', 'Vassar College', 'Poughkeepsie', 'NY', 'ny', 20),
  ('bard', 'Bard College', 'Annandale-on-Hudson', 'NY', 'ny', 20),
  ('ithaca', 'Ithaca College', 'Ithaca', 'NY', 'ny', 20),
  ('st-lawrence', 'St. Lawrence University', 'Canton', 'NY', 'ny', 20),
  ('rpi', 'Rensselaer Polytechnic Institute', 'Troy', 'NY', 'ny', 20),
  ('binghamton', 'Binghamton University (SUNY)', 'Binghamton', 'NY', 'ny', 20),
  ('suny-albany', 'University at Albany (SUNY)', 'Albany', 'NY', 'ny', 20),
  ('suny-buffalo', 'University at Buffalo (SUNY)', 'Buffalo', 'NY', 'ny', 20),
  ('suny-geneseo', 'SUNY Geneseo', 'Geneseo', 'NY', 'ny', 20),
  ('suny-cortland', 'SUNY Cortland', 'Cortland', 'NY', 'ny', 20),
  ('princeton', 'Princeton University', 'Princeton', 'NJ', 'nj', 30),
  ('rutgers', 'Rutgers University', 'New Brunswick', 'NJ', 'nj', 30),
  ('seton-hall', 'Seton Hall University', 'South Orange', 'NJ', 'nj', 30),
  ('stevens', 'Stevens Institute of Technology', 'Hoboken', 'NJ', 'nj', 30),
  ('tcnj', 'The College of New Jersey', 'Ewing', 'NJ', 'nj', 30),
  ('montclair-state', 'Montclair State University', 'Montclair', 'NJ', 'nj', 30),
  ('rowan', 'Rowan University', 'Glassboro', 'NJ', 'nj', 30),
  ('fdu', 'Fairleigh Dickinson University', 'Teaneck', 'NJ', 'nj', 30),
  ('ramapo', 'Ramapo College of New Jersey', 'Mahwah', 'NJ', 'nj', 30),
  ('monmouth', 'Monmouth University', 'West Long Branch', 'NJ', 'nj', 30),
  ('yale', 'Yale University', 'New Haven', 'CT', 'ct', 40),
  ('uconn', 'University of Connecticut', 'Storrs', 'CT', 'ct', 40),
  ('trinity-ct', 'Trinity College', 'Hartford', 'CT', 'ct', 40),
  ('wesleyan', 'Wesleyan University', 'Middletown', 'CT', 'ct', 40),
  ('fairfield', 'Fairfield University', 'Fairfield', 'CT', 'ct', 40),
  ('quinnipiac', 'Quinnipiac University', 'Hamden', 'CT', 'ct', 40),
  ('conn-college', 'Connecticut College', 'New London', 'CT', 'ct', 40),
  ('sacred-heart', 'Sacred Heart University', 'Fairfield', 'CT', 'ct', 40),
  ('hartford', 'University of Hartford', 'West Hartford', 'CT', 'ct', 40),
  ('harvard', 'Harvard University', 'Cambridge', 'MA', 'ma', 50),
  ('mit', 'Massachusetts Institute of Technology', 'Cambridge', 'MA', 'ma', 50),
  ('bc', 'Boston College', 'Chestnut Hill', 'MA', 'ma', 50),
  ('bu', 'Boston University', 'Boston', 'MA', 'ma', 50),
  ('northeastern', 'Northeastern University', 'Boston', 'MA', 'ma', 50),
  ('tufts', 'Tufts University', 'Medford', 'MA', 'ma', 50),
  ('umass-amherst', 'UMass Amherst', 'Amherst', 'MA', 'ma', 50),
  ('umass-boston', 'UMass Boston', 'Boston', 'MA', 'ma', 50),
  ('emerson', 'Emerson College', 'Boston', 'MA', 'ma', 50),
  ('suffolk', 'Suffolk University', 'Boston', 'MA', 'ma', 50),
  ('bentley', 'Bentley University', 'Waltham', 'MA', 'ma', 50),
  ('babson', 'Babson College', 'Wellesley', 'MA', 'ma', 50),
  ('brandeis', 'Brandeis University', 'Waltham', 'MA', 'ma', 50),
  ('holy-cross', 'College of the Holy Cross', 'Worcester', 'MA', 'ma', 50),
  ('williams', 'Williams College', 'Williamstown', 'MA', 'ma', 50),
  ('amherst', 'Amherst College', 'Amherst', 'MA', 'ma', 50),
  ('smith', 'Smith College', 'Northampton', 'MA', 'ma', 50),
  ('mount-holyoke', 'Mount Holyoke College', 'South Hadley', 'MA', 'ma', 50),
  ('wellesley', 'Wellesley College', 'Wellesley', 'MA', 'ma', 50),
  ('clark', 'Clark University', 'Worcester', 'MA', 'ma', 50),
  ('wpi', 'Worcester Polytechnic Institute', 'Worcester', 'MA', 'ma', 50),
  ('stonehill', 'Stonehill College', 'Easton', 'MA', 'ma', 50),
  ('johns-hopkins', 'Johns Hopkins University', 'Baltimore', 'MD', 'northeast', 60),
  ('maryland', 'University of Maryland', 'College Park', 'MD', 'northeast', 60),
  ('georgetown', 'Georgetown University', 'Washington', 'DC', 'northeast', 60),
  ('gwu', 'George Washington University', 'Washington', 'DC', 'northeast', 60),
  ('american', 'American University', 'Washington', 'DC', 'northeast', 60),
  ('penn', 'University of Pennsylvania', 'Philadelphia', 'PA', 'northeast', 60),
  ('villanova', 'Villanova University', 'Villanova', 'PA', 'northeast', 60),
  ('temple', 'Temple University', 'Philadelphia', 'PA', 'northeast', 60),
  ('drexel', 'Drexel University', 'Philadelphia', 'PA', 'northeast', 60),
  ('lehigh', 'Lehigh University', 'Bethlehem', 'PA', 'northeast', 60),
  ('bucknell', 'Bucknell University', 'Lewisburg', 'PA', 'northeast', 60),
  ('lafayette', 'Lafayette College', 'Easton', 'PA', 'northeast', 60),
  ('penn-state', 'Penn State University', 'University Park', 'PA', 'northeast', 60),
  ('pitt', 'University of Pittsburgh', 'Pittsburgh', 'PA', 'northeast', 60),
  ('brown', 'Brown University', 'Providence', 'RI', 'northeast', 60),
  ('providence', 'Providence College', 'Providence', 'RI', 'northeast', 60),
  ('uri', 'University of Rhode Island', 'Kingston', 'RI', 'northeast', 60),
  ('dartmouth', 'Dartmouth College', 'Hanover', 'NH', 'northeast', 60),
  ('unh', 'University of New Hampshire', 'Durham', 'NH', 'northeast', 60),
  ('uvm', 'University of Vermont', 'Burlington', 'VT', 'northeast', 60),
  ('middlebury', 'Middlebury College', 'Middlebury', 'VT', 'northeast', 60),
  ('bowdoin', 'Bowdoin College', 'Brunswick', 'ME', 'northeast', 60),
  ('colby', 'Colby College', 'Waterville', 'ME', 'northeast', 60),
  ('bates', 'Bates College', 'Lewiston', 'ME', 'northeast', 60),
  ('delaware', 'University of Delaware', 'Newark', 'DE', 'northeast', 60),
  ('virginia', 'University of Virginia', 'Charlottesville', 'VA', 'national', 70),
  ('virginia-tech', 'Virginia Tech', 'Blacksburg', 'VA', 'national', 70),
  ('duke', 'Duke University', 'Durham', 'NC', 'national', 70),
  ('unc', 'University of North Carolina', 'Chapel Hill', 'NC', 'national', 70),
  ('elon', 'Elon University', 'Elon', 'NC', 'national', 70),
  ('vanderbilt', 'Vanderbilt University', 'Nashville', 'TN', 'national', 70),
  ('emory', 'Emory University', 'Atlanta', 'GA', 'national', 70),
  ('georgia', 'University of Georgia', 'Athens', 'GA', 'national', 70),
  ('clemson', 'Clemson University', 'Clemson', 'SC', 'national', 70),
  ('alabama', 'University of Alabama', 'Tuscaloosa', 'AL', 'national', 70),
  ('tulane', 'Tulane University', 'New Orleans', 'LA', 'national', 70),
  ('miami', 'University of Miami', 'Coral Gables', 'FL', 'national', 70),
  ('florida', 'University of Florida', 'Gainesville', 'FL', 'national', 70),
  ('florida-state', 'Florida State University', 'Tallahassee', 'FL', 'national', 70),
  ('michigan', 'University of Michigan', 'Ann Arbor', 'MI', 'national', 70),
  ('michigan-state', 'Michigan State University', 'East Lansing', 'MI', 'national', 70),
  ('ohio-state', 'Ohio State University', 'Columbus', 'OH', 'national', 70),
  ('indiana', 'Indiana University', 'Bloomington', 'IN', 'national', 70),
  ('notre-dame', 'University of Notre Dame', 'Notre Dame', 'IN', 'national', 70),
  ('wisconsin', 'University of Wisconsin–Madison', 'Madison', 'WI', 'national', 70),
  ('illinois', 'University of Illinois', 'Urbana-Champaign', 'IL', 'national', 70),
  ('northwestern', 'Northwestern University', 'Evanston', 'IL', 'national', 70),
  ('chicago', 'University of Chicago', 'Chicago', 'IL', 'national', 70),
  ('wash-u', 'Washington University in St. Louis', 'St. Louis', 'MO', 'national', 70),
  ('texas', 'University of Texas at Austin', 'Austin', 'TX', 'national', 70),
  ('smu', 'Southern Methodist University', 'Dallas', 'TX', 'national', 70),
  ('colorado', 'University of Colorado Boulder', 'Boulder', 'CO', 'national', 70),
  ('arizona-state', 'Arizona State University', 'Tempe', 'AZ', 'national', 70),
  ('arizona', 'University of Arizona', 'Tucson', 'AZ', 'national', 70),
  ('usc', 'University of Southern California', 'Los Angeles', 'CA', 'national', 70),
  ('ucla', 'UCLA', 'Los Angeles', 'CA', 'national', 70),
  ('berkeley', 'UC Berkeley', 'Berkeley', 'CA', 'national', 70),
  ('stanford', 'Stanford University', 'Stanford', 'CA', 'national', 70),
  ('san-diego', 'UC San Diego', 'La Jolla', 'CA', 'national', 70),
  ('washington', 'University of Washington', 'Seattle', 'WA', 'national', 70),
  ('mcgill', 'McGill University', 'Montreal', 'QC', 'national', 70)
on conflict (slug) do update set
  name       = excluded.name,
  city       = excluded.city,
  state      = excluded.state,
  region     = excluded.region,
  sort_order = excluded.sort_order;

-- ---------- profiles: college fields ----------
-- Both nullable: the onboarding step is optional and skippable, and a user
-- who skips can fill it in later from Edit profile.
-- on delete set null: removing a college row must never delete a profile.

alter table profiles add column if not exists college_slug text
  references colleges (slug) on update cascade on delete set null;

alter table profiles add column if not exists class_year smallint
  check (class_year is null or (class_year between 1950 and 2100));

comment on column profiles.college_slug is 'FK to colleges.slug. Null = not answered; the field is optional.';
comment on column profiles.class_year is 'Graduation year. class_year < current year means alum. Null = not answered.';

-- Supports "who else is from my school" without scanning profiles.
create index if not exists profiles_college_idx on profiles (college_slug) where college_slug is not null;
