-- ENDZ venue expansion (additive; generated by enrich-venues.mjs expand)
insert into venues (name, type, price, lat, lng) values
  ('96 Tears', 'bar', null, 40.7258393, -73.98348510000001),
  ('Double Down Saloon', 'bar', '$', 40.722516, -73.98574099999999),
  ('Lovers of Today', 'lounge', null, 40.7258254, -73.9834216),
  ('Banshee', 'bar', null, 40.728176399999995, -73.9853309),
  ('Sake Bar Decibel', 'bar', '$$', 40.729300599999995, -73.9877458),
  ('Barcade', 'bar', '$$', 40.72911560000001, -73.98953929999999),
  ('Blue & Gold Tavern', 'bar', '$', 40.727325, -73.9862831),
  ('Downtown Social', 'bar', null, 40.729528300000005, -73.98738759999999),
  ('Otto''s Shrunken Head', 'bar', '$', 40.7294629, -73.9786985);
